spring:
  datasource:
    username: root
    password: 981028
    url: jdbc:mysql://localhost:3306/news?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    favicon:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    net.xi.news: debug
  file:
    name: log/new-dev.log

server:
  port: 8088

swagger:
  show: true
